# https://github.com/vllm-project/production-stack/blob/main/helm/values.yaml
servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
    - name: "llama"
      repository: "vllm/vllm-openai"
      # tag: "latest"
      tag: "v0.17.0"
      # modelURL: "meta-llama/Llama-3.1-8B-Instruct"
      modelURL: "hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4"
      replicaCount: 1

      requestCPU: 10
      requestMemory: "16Gi"
      requestGPU: 1
      pvcStorage: "50Gi"
      pvcAccessMode:
        - ReadWriteOnce
      
      # initContainer:
      #   name: debug
      #   image: busybox:latest
      #   args: ["sleep", "9999"]

      # Enable KEDA autoscaling
      podAnnotations:
        sidecar.opentelemetry.io/inject: "otel-sidecar-template"
      keda:
        enabled: true
        triggers:
          - type: external
            metadata:
              scalerAddress: "keda-otel-scaler.keda.svc:4318"
              metricQuery: "sum(vllm:kv_cache_usage_perc)"
              operationOverTime: "avg"
              targetValue: ".5" # for scaling 1 -> 2
          - type: external
            metadata:
              scalerAddress: "keda-otel-scaler.keda.svc:4318"
              metricQuery: "sum(vllm:num_requests_waiting)"
              operationOverTime: "avg"
              targetValue: "30" # for scaling 2 -> 3
        minReplicaCount: 1
        maxReplicaCount: 3
        fallback:
          failureThreshold: 10
          replicas: 1
        advanced:
          horizontalPodAutoscalerConfig:
            behavior:
              scaleDown:
                # this should be higher in prod
                stabilizationWindowSeconds: 1200
              scaleUp:
                # this should be much higher in prod
                stabilizationWindowSeconds: 1

      vllmConfig:
        enableChunkedPrefill: false
        enablePrefixCaching: false
        maxModelLen: 4096
        quantization: "awq"
        dtype: "half"

        # extraArgs: ["--gpu-memory-utilization", "0.85", "--dtype", "half"]
        extraArgs: [
          "--gpu-memory-utilization", "0.85",
          "--max-num-seqs", "1",
          "--enforce-eager",
        ]

      # pass this as --set arg so that it doesn't end up in git
      # hf_token: hf_**
routerSpec:
  startupProbe:
    initialDelaySeconds: 30
    failureThreshold: 120
